name: Run Python Code
on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 0-9 * * 1-5"

  workflow_dispatch:
jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python writetxt.py # 이곳에 실제 파이썬 파일명을 적어주세요.
      - name : Run Python script2
        env:
          WEBHOOK_MAINNOTICES: ${{ secrets.DISCORD_WEBHOOKS_MAIN_NOTICES}}
        run: python notifyNotice.py