name: Run Python Code
on:
  schedule:
    - cron: "0,10,20,30,40,50 0-11 * * 1-5"
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name : Run notifyMainNotice
        env:
          WEBHOOK_MAINNOTICES: ${{ secrets.DISCORD_WEBHOOKS_MAIN_NOTICES}}
        run: python notifyMainNotice.py

      - name : Run notifyAaiBulletin
        env:
          WEBHOOK_AAIBULLETIN: ${{ secrets.DISCORD_WEBHOOKS_AAI_BULLETIN}}
        run: python notifyAaiBulletin.py        
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update "
          git push https://${{secrets.GH_TOKEN}}@github.com/SeungPyo-Jeon/UniversityAnnouncementAlarm.git HEAD:main
